### ISSUE TITLE
FE - Implement Session Tracking for Non-Signed-Up Users

### ISSUE THREAD

**Issue by stevexero** [stevexero/box_valet#25]
To track the duration of time a user spends on the site before signing up or exiting the site.

- Implement a timer that starts when the user lands on the page and stops when they leave.

- Use the beforeunload event to capture the session duration and send it to the backend before the user exits the page.

**Comment by stevexero** [comment]
Closing this issue as the Umami analytics has already been implemented

**Comment by Cservice01** [comment]
🥇
